//! Surfacing for the L1/L3 hierarchy: god-node (community) Obsidian notes and a
//! navigable "feature map" HTML.
//!
//! These render the *persisted* hierarchy (no re-index, no embedder), so they
//! are regenerated by `chaos refresh` / `chaos obsidian`. The feature map shows
//! communities as nodes, the quotient graph as edges, and drills into each
//! feature's summary + member symbols. Blade Runner theme, owned here in Rust.

use crate::export_util::escape_script_json;
use anyhow::Result;
use serde::Serialize;
use serde_json::json;
use std::{
    collections::HashMap,
    fs,
    path::{Path, PathBuf},
};
use uuid::Uuid;

/// The full feature hierarchy for a repo (feature communities only).
#[derive(Debug, Clone, Serialize)]
pub struct CommunityHierarchy {
    pub repo_name: String,
    pub communities: Vec<CommunityDetail>,
    pub edges: Vec<QuotientEdgeDetail>,
}

#[derive(Debug, Clone, Serialize)]
pub struct CommunityDetail {
    pub id: Uuid,
    pub label: String,
    pub summary: Option<String>,
    pub member_count: i32,
    /// `(name, kind, file)` for representative members.
    pub top_members: Vec<(String, String, String)>,
}

#[derive(Debug, Clone, Serialize)]
pub struct QuotientEdgeDetail {
    pub source: Uuid,
    pub target: Uuid,
    pub kind: String,
    pub weight: f64,
    pub edge_count: i32,
}

#[derive(Debug, Clone, Serialize)]
pub struct HierarchyExportSummary {
    pub community_notes: usize,
    pub feature_map_html: Option<PathBuf>,
}

impl CommunityHierarchy {
    pub fn is_empty(&self) -> bool {
        self.communities.is_empty()
    }
}

/// Write god-node notes (one per feature community) + a "Feature Map" index into
/// `vault/Communities`, and the navigable `feature-map.html` into `features_dir`.
pub fn write_hierarchy(
    vault: &Path,
    features_dir: &Path,
    hierarchy: &CommunityHierarchy,
) -> Result<HierarchyExportSummary> {
    if hierarchy.is_empty() {
        return Ok(HierarchyExportSummary {
            community_notes: 0,
            feature_map_html: None,
        });
    }
    let community_notes = write_community_notes(vault, hierarchy)?;
    fs::create_dir_all(features_dir)?;
    let html = features_dir.join("feature-map.html");
    write_feature_map_html(&html, hierarchy)?;
    Ok(HierarchyExportSummary {
        community_notes,
        feature_map_html: Some(html),
    })
}

fn note_name(detail: &CommunityDetail) -> String {
    let id = detail.id.to_string();
    format!(
        "Community - {} - {}",
        safe_filename(&detail.label),
        &id[..8]
    )
}

fn write_community_notes(vault: &Path, hierarchy: &CommunityHierarchy) -> Result<usize> {
    let dir = vault.join("Communities");
    fs::create_dir_all(&dir)?;

    let note_by_id: HashMap<Uuid, String> = hierarchy
        .communities
        .iter()
        .map(|c| (c.id, note_name(c)))
        .collect();

    // Peer links from the quotient graph (both directions).
    let mut peers: HashMap<Uuid, Vec<(Uuid, String, f64)>> = HashMap::new();
    for edge in &hierarchy.edges {
        if note_by_id.contains_key(&edge.source) && note_by_id.contains_key(&edge.target) {
            peers.entry(edge.source).or_default().push((
                edge.target,
                edge.kind.clone(),
                edge.weight,
            ));
            peers.entry(edge.target).or_default().push((
                edge.source,
                edge.kind.clone(),
                edge.weight,
            ));
        }
    }

    for community in &hierarchy.communities {
        let name = &note_by_id[&community.id];
        let mut body = String::new();
        body.push_str("---\n");
        body.push_str("kind: community\n");
        body.push_str(&format!("id: {}\n", community.id));
        body.push_str(&format!("member_count: {}\n", community.member_count));
        body.push_str("---\n\n");
        body.push_str(&format!("# {}\n\n", community.label));
        body.push_str(&format!(
            "Feature community of **{}** symbols.\n\n",
            community.member_count
        ));
        if let Some(summary) = &community.summary {
            body.push_str("## Summary\n\n");
            body.push_str(summary.trim());
            body.push_str("\n\n");
        }

        body.push_str("## Key members\n\n");
        if community.top_members.is_empty() {
            body.push_str("_None._\n\n");
        } else {
            for (mname, kind, file) in &community.top_members {
                if file.is_empty() {
                    body.push_str(&format!("- `{mname}` ({kind})\n"));
                } else {
                    body.push_str(&format!("- `{mname}` ({kind}) — `{file}`\n"));
                }
            }
            body.push('\n');
        }

        body.push_str("## Connected features\n\n");
        let mut links = peers.remove(&community.id).unwrap_or_default();
        links.sort_by(|a, b| {
            b.2.partial_cmp(&a.2)
                .unwrap_or(std::cmp::Ordering::Equal)
                .then(a.0.cmp(&b.0))
        });
        if links.is_empty() {
            body.push_str("_None._\n");
        } else {
            let mut seen = std::collections::HashSet::new();
            for (target, kind, _) in links {
                if !seen.insert(target) {
                    continue;
                }
                if let Some(target_note) = note_by_id.get(&target) {
                    body.push_str(&format!("- [[{target_note}]] _(via {kind})_\n"));
                }
            }
        }

        fs::write(dir.join(format!("{name}.md")), body)?;
    }

    // Feature Map index note.
    let mut index = String::new();
    index.push_str(&format!("# {} — Feature Map\n\n", hierarchy.repo_name));
    index.push_str(&format!(
        "{} feature communities, {} quotient links. Open `feature-map.html` for the interactive view.\n\n",
        hierarchy.communities.len(),
        hierarchy.edges.len()
    ));
    let mut ordered: Vec<&CommunityDetail> = hierarchy.communities.iter().collect();
    ordered.sort_by(|a, b| {
        b.member_count
            .cmp(&a.member_count)
            .then(a.label.cmp(&b.label))
    });
    for community in ordered {
        index.push_str(&format!(
            "- [[{}]] — {} symbols\n",
            note_by_id[&community.id], community.member_count
        ));
    }
    fs::write(vault.join("Feature Map.md"), index)?;

    Ok(hierarchy.communities.len())
}

pub fn write_feature_map_html(path: &Path, hierarchy: &CommunityHierarchy) -> Result<()> {
    let data = json!({
        "repo": hierarchy.repo_name,
        "communities": hierarchy.communities,
        "edges": hierarchy.edges,
    });
    let json = serde_json::to_string(&data)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(
        path,
        FEATURE_MAP_HTML
            .replace("__THEME__", crate::theme::THEME_CSS)
            .replace(
                "__BRAND_TOPBAR__",
                &crate::theme::render_brand(&crate::theme::Brand::default(), "topbar"),
            )
            .replace(
                "__BRAND_FOOTER__",
                &crate::theme::render_brand(&crate::theme::Brand::default(), "footer"),
            )
            .replace("__DATA__", &escape_script_json(&json)),
    )?;
    Ok(())
}

fn safe_filename(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || matches!(ch, ' ' | '-' | '_' | '.') {
            out.push(ch);
        } else {
            out.push('-');
        }
    }
    let out = out
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .trim_matches(['.', '-', ' '])
        .to_string();
    if out.is_empty() {
        "feature".into()
    } else {
        out.chars().take(80).collect()
    }
}

const FEATURE_MAP_HTML: &str = r##"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Feature Map</title>
<style>
__THEME__
/* ===== feature map components (light editorial) ===== */
.app{display:grid;grid-template-columns:300px 1fr 360px;height:calc(100vh - 64px);min-height:520px;border-top:var(--border-hairline)}
.panel{overflow:auto;padding:20px;border-right:var(--border-hairline);background:var(--color-surface-1)}
.details{border-right:0;border-left:var(--border-hairline);background:var(--bg-page)}
.map-title{font:var(--type-h4);color:var(--color-ink-700);margin:0 0 6px;letter-spacing:-.01em}
.muted{color:var(--fg-tertiary);font:var(--type-body-sm);line-height:1.5}
.feat{border:var(--border-hairline);border-radius:var(--radius-md);background:var(--bg-page);padding:11px 13px;margin-top:10px;cursor:pointer;font:var(--type-body-sm);box-shadow:var(--shadow-xs);transition:border-color .15s,box-shadow .15s}
.feat:hover,.feat.sel{border-color:var(--color-blue-400);box-shadow:var(--shadow-sm)}
.feat.sel{border-color:var(--color-blue-700);box-shadow:0 0 0 1px var(--color-blue-700),var(--shadow-sm)}
.feat b{color:var(--color-blue-700);font-weight:500}.feat .m{color:var(--fg-tertiary);font:var(--type-body-xs);margin-top:2px}
#stage{position:relative;overflow:hidden;background:var(--bg-page)}
svg{width:100%;height:100%;display:block}
.node{cursor:pointer}.node circle{transition:stroke-width .1s,stroke .1s}
.node:hover circle,.node.sel circle{stroke:var(--color-blue-700);stroke-width:2.5}
.elabel,.nlabel{font-size:10px;fill:var(--fg-tertiary)}
.nlabel{fill:var(--color-ink-600);font-size:11px;font-family:var(--font-body)}
.map-sec{font:var(--type-h6);margin:0 0 8px;color:var(--color-blue-700);font-weight:500}
pre{white-space:pre-wrap;background:var(--color-surface-2);border:var(--border-soft);border-radius:var(--radius-md);padding:14px;font:var(--type-body-sm);font-family:var(--font-mono);color:var(--color-ink-600);max-height:240px;overflow:auto}
.sym{display:inline-block;border:var(--border-hairline);border-radius:var(--radius-pill);padding:4px 10px;margin:4px 5px 0 0;font:var(--type-body-xs);background:var(--color-surface-1);color:var(--color-ink-500)}.sym .k{color:var(--fg-tertiary);font-size:10px}
.pill{display:inline-block;border:1px solid var(--color-blue-100);border-radius:var(--radius-pill);padding:3px 10px;margin:3px 4px 0 0;color:var(--color-blue-700);background:var(--color-blue-50);font:var(--type-body-xs);cursor:pointer;transition:border-color .15s,background .15s}
.pill:hover{border-color:var(--color-blue-400);background:var(--color-blue-100)}
</style>
</head>
<body data-chaos-feature-map>
<div class="topbar"><div class="wrap">__BRAND_TOPBAR__<span class="crumb">Feature map<span class="sep">&rsaquo;</span><b>features</b></span><span class="sp"></span><span class="pilltag">Feature map</span></div></div>
<div class="app">
  <aside class="panel">
    <h1 class="map-title">Feature Map</h1>
    <div id="repo" class="muted"></div>
    <div id="list"></div>
  </aside>
  <main id="stage"><svg id="svg"></svg></main>
  <aside class="panel details">
    <div id="detail"><div class="muted">Select a feature to inspect its summary, members, and connections.</div></div>
  </aside>
</div>
<footer><div class="wrap">__BRAND_FOOTER__<span class="sp"></span><span class="meta">generated by Chaos Substrate</span></div></footer>
<script type="application/json" id="chaos-feature-map-data">__DATA__</script>
<script>
(function(){
var D=JSON.parse(document.getElementById("chaos-feature-map-data").textContent);
function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
var C=D.communities||[],E=D.edges||[];
document.getElementById("repo").textContent=(D.repo||"")+" — "+C.length+" features, "+E.length+" links";
var byId={};C.forEach(function(c){byId[c.id]=c;});
var maxM=Math.max(1,Math.max.apply(null,C.map(function(c){return c.member_count;})));
// Deterministic circular layout.
var svg=document.getElementById("svg"),stage=document.getElementById("stage");
var W=stage.clientWidth||900,H=stage.clientHeight||700;
svg.setAttribute("viewBox","0 0 "+W+" "+H);
var cx=W/2,cy=H/2,R=Math.min(W,H)/2-70;
var pos={};
C.forEach(function(c,i){var a=-Math.PI/2+2*Math.PI*i/C.length;pos[c.id]={x:cx+R*Math.cos(a),y:cy+R*Math.sin(a)};});
var maxW=Math.max(1,Math.max.apply(null,E.map(function(e){return e.weight;})||[1]));
var NS="http://www.w3.org/2000/svg";
function el(n,a){var e=document.createElementNS(NS,n);for(var k in a)e.setAttribute(k,a[k]);return e;}
// edges
E.forEach(function(e){var s=pos[e.source],t=pos[e.target];if(!s||!t)return;var ln=el("line",{x1:s.x,y1:s.y,x2:t.x,y2:t.y,stroke:"#84b2e9",["stroke-opacity"]:(0.18+0.6*e.weight/maxW).toFixed(3),["stroke-width"]:Math.max(0.6,2.5*e.weight/maxW)});ln.dataset.s=e.source;ln.dataset.t=e.target;svg.appendChild(ln);});
// nodes
C.forEach(function(c){var p=pos[c.id];var g=el("g",{class:"node"});g.dataset.id=c.id;var r=7+18*Math.sqrt(c.member_count/maxM);g.appendChild(el("circle",{cx:p.x,cy:p.y,r:r,fill:"#e9f1fa",stroke:"#4475a0",["stroke-width"]:1.4}));var tx=el("text",{x:p.x,y:p.y-r-4,["text-anchor"]:"middle",class:"nlabel"});tx.textContent=(c.label||"").slice(0,22);g.appendChild(tx);g.addEventListener("click",function(){select(c.id);});svg.appendChild(g);});
var list=document.getElementById("list");
C.slice().sort(function(a,b){return b.member_count-a.member_count;}).forEach(function(c){var d=document.createElement("div");d.className="feat";d.dataset.id=c.id;d.innerHTML='<b>'+esc(c.label)+'</b><div class="m">'+c.member_count+' symbols</div>';d.addEventListener("click",function(){select(c.id);});list.appendChild(d);});
function neighbors(id){var n=[];E.forEach(function(e){if(e.source===id&&byId[e.target])n.push([e.target,e.kind,e.weight]);if(e.target===id&&byId[e.source])n.push([e.source,e.kind,e.weight]);});return n;}
function select(id){
  var c=byId[id];if(!c)return;
  Array.prototype.forEach.call(document.querySelectorAll(".node"),function(g){g.classList.toggle("sel",g.dataset.id===id);});
  Array.prototype.forEach.call(document.querySelectorAll(".feat"),function(g){g.classList.toggle("sel",g.dataset.id===id);});
  Array.prototype.forEach.call(document.querySelectorAll("line"),function(l){var on=l.dataset.s===id||l.dataset.t===id;l.setAttribute("stroke",on?"#1b589c":"#84b2e9");l.setAttribute("stroke-opacity",on?"0.85":"0.22");});
  var nb=neighbors(id).sort(function(a,b){return b[2]-a[2];});
  var seen={};var nbHtml=nb.filter(function(x){if(seen[x[0]])return false;seen[x[0]]=1;return true;}).map(function(x){return '<span class="pill" data-go="'+x[0]+'">'+esc(byId[x[0]].label)+'</span>';}).join("");
  var syms=(c.top_members||[]).map(function(m){return '<span class="sym">'+esc(m[0])+' <span class="k">'+esc(m[1])+'</span></span>';}).join("");
  document.getElementById("detail").innerHTML='<h2 class="map-sec">'+esc(c.label)+'</h2><div class="muted">'+c.member_count+' symbols</div>'+
    (c.summary?'<pre>'+esc(c.summary)+'</pre>':'')+
    '<h2 class="map-sec" style="margin-top:14px">Members</h2><div>'+(syms||'<span class="muted">—</span>')+'</div>'+
    '<h2 class="map-sec" style="margin-top:14px">Connected features</h2><div>'+(nbHtml||'<span class="muted">none</span>')+'</div>';
  Array.prototype.forEach.call(document.querySelectorAll("[data-go]"),function(p){p.addEventListener("click",function(){select(p.dataset.go);});});
}
if(C.length)select(C[0].id);
})();
</script>
</body>
</html>
"##;

#[cfg(test)]
mod tests {
    use super::*;

    fn hierarchy() -> CommunityHierarchy {
        CommunityHierarchy {
            repo_name: "demo".into(),
            communities: vec![
                CommunityDetail {
                    id: Uuid::from_u128(1),
                    label: "auth · login".into(),
                    summary: Some("Feature: auth".into()),
                    member_count: 4,
                    top_members: vec![("login".into(), "function".into(), "auth.rs".into())],
                },
                CommunityDetail {
                    id: Uuid::from_u128(2),
                    label: "db · pool".into(),
                    summary: None,
                    member_count: 3,
                    top_members: vec![],
                },
            ],
            edges: vec![QuotientEdgeDetail {
                source: Uuid::from_u128(1),
                target: Uuid::from_u128(2),
                kind: "calls".into(),
                weight: 2.0,
                edge_count: 3,
            }],
        }
    }

    #[test]
    fn writes_notes_and_cross_links() {
        let dir = tempfile::tempdir().unwrap();
        let vault = dir.path().join("vault");
        let features = dir.path().join("features");
        let summary = write_hierarchy(&vault, &features, &hierarchy()).unwrap();
        assert_eq!(summary.community_notes, 2);
        assert!(summary.feature_map_html.is_some());
        assert!(vault.join("Feature Map.md").exists());
        // The auth note links to the db community note.
        let notes = fs::read_dir(vault.join("Communities")).unwrap();
        let auth = notes
            .filter_map(|e| e.ok())
            .map(|e| fs::read_to_string(e.path()).unwrap())
            .find(|s| s.contains("# auth · login"))
            .unwrap();
        assert!(auth.contains("Connected features"));
        // Link uses the sanitized peer note name (· → -).
        assert!(auth.contains("[[Community - db - pool"));
    }

    #[test]
    fn feature_map_html_has_markers() {
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("feature-map.html");
        write_feature_map_html(&out, &hierarchy()).unwrap();
        let html = fs::read_to_string(&out).unwrap();
        assert!(html.contains("data-chaos-feature-map"));
        assert!(html.contains("chaos-feature-map-data"));
        assert!(html.contains("Feature Map"));
    }

    #[test]
    fn empty_hierarchy_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let h = CommunityHierarchy {
            repo_name: "x".into(),
            communities: vec![],
            edges: vec![],
        };
        let summary = write_hierarchy(&dir.path().join("v"), &dir.path().join("f"), &h).unwrap();
        assert_eq!(summary.community_notes, 0);
        assert!(summary.feature_map_html.is_none());
    }
}
